### ISSUE TITLE
Windows, Mac, Linux?

### ISSUE THREAD

**Issue by dxcore35** [Liamballin/ObsidianBookmark#1]
I see Obisdian-server.exe. Does it works only on windows.
But I don't see anything mentioned in description.

**Comment by Liamballin** [comment]
I've added a mac package to the release, but as I'm on a windows machine I can't code sign. I'm also not able to test that it works.
If you are after the server on a different platform, or if the new mac release doesn't work, you could clone this repo and package it yourself. Running `electron-packager .` in the server folder will create an executable for your specific platform and architecture.
